version: '3'

services:
  app:
    container_name: 'remote_access'
    build: .
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: npm run start
    restart: always
    networks:
      proxy_network:
        ipv4_address: 172.30.0.20

networks:
  proxy_network:
    external: true