version: '3'

services:
  app:
    container_name: 'remote_access'
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /app
    command:
#      - sh -c "npm install && npm run start"
    restart: always
    networks:
      proxy_network:
        ipv4_address: 172.30.0.20

networks:
  proxy_network:
    external: true